{"@t":"2023-03-01T04:57:36.3776961Z","@mt":"Registered 3 endpoints in 247 milliseconds.","SourceContext":"FastEndpoints.StartupTimer","Application":"messages-service"}
{"@t":"2023-03-01T04:57:36.5622237Z","@mt":"No validators found in the system!","SourceContext":"FastEndpoints.Swagger.ValidationSchemaProcessor","Application":"messages-service"}
{"@t":"2023-03-01T04:57:36.6619342Z","@mt":"Connecting to Redis endpoints: {Endpoints}. Using Server Name: {ServerName}","Endpoints":"localhost","ServerName":"DESKTOP-G3RIR5H_274128caecb844ae901f4613ac5368f0","EventId":{"Id":1,"Name":"ConnectingToEndpoints"},"SourceContext":"Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager","Application":"messages-service"}
{"@t":"2023-03-01T04:57:36.8765540Z","@mt":"Connected to Redis.","EventId":{"Id":2,"Name":"Connected"},"SourceContext":"Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager","Application":"messages-service"}
{"@t":"2023-03-01T04:57:38.9433002Z","@mt":"Configured endpoint {Endpoint}, Consumer: {ConsumerType}","Endpoint":"AppUserLoggedInEvent-Messages","ConsumerType":"Messages.API.Consumers.AppUserLoggedInConsumer","SourceContext":"MassTransit","Application":"messages-service"}
{"@t":"2023-03-01T04:57:39.2495272Z","@mt":"Now listening on: {address}","address":"https://localhost:6002","EventId":{"Id":14,"Name":"ListeningOnAddress"},"SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T04:57:39.2504379Z","@mt":"Now listening on: {address}","address":"http://localhost:5002","EventId":{"Id":14,"Name":"ListeningOnAddress"},"SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T04:57:39.2513169Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T04:57:39.2521678Z","@mt":"Hosting environment: {EnvName}","EnvName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T04:57:39.2527970Z","@mt":"Content root path: {ContentRoot}","ContentRoot":"C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Messages.API","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T04:57:39.3643102Z","@mt":"Bus started: {HostAddress}","HostAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"messages-service"}
{"@t":"2023-03-01T08:07:15.1191042Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T08:07:15.2041384Z","@mt":"Bus stopped: {HostAddress}","HostAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"messages-service"}
{"@t":"2023-03-01T09:43:53.4805757Z","@mt":"Registered 3 endpoints in 189 milliseconds.","SourceContext":"FastEndpoints.StartupTimer","Application":"messages-service"}
{"@t":"2023-03-01T09:43:53.6402806Z","@mt":"No validators found in the system!","SourceContext":"FastEndpoints.Swagger.ValidationSchemaProcessor","Application":"messages-service"}
{"@t":"2023-03-01T09:43:53.7173258Z","@mt":"Connecting to Redis endpoints: {Endpoints}. Using Server Name: {ServerName}","Endpoints":"localhost","ServerName":"DESKTOP-G3RIR5H_c3cc6691148c4b29a7ce24dbcd633251","EventId":{"Id":1,"Name":"ConnectingToEndpoints"},"SourceContext":"Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager","Application":"messages-service"}
{"@t":"2023-03-01T09:43:57.8909179Z","@mt":"Error connecting to Redis.","@l":"Error","@x":"StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 4s ago, v: 2.2.4.27433\r\n   at StackExchange.Redis.ConnectionMultiplexer.ConnectImplAsync(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 861\r\n   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisOptions.ConnectAsync(TextWriter log)\r\n   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.EnsureRedisServerConnection()","EventId":{"Id":14,"Name":"ErrorConnecting"},"SourceContext":"Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager","Application":"messages-service","ExceptionDetail":{"HResult":-2146233088,"Message":"It was not possible to connect to the redis server(s). UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 4s ago, v: 2.2.4.27433","Source":"StackExchange.Redis","TargetSite":"Void MoveNext()","FailureType":"UnableToConnect","CommandStatus":"Unknown","Type":"StackExchange.Redis.RedisConnectionException"}}
{"@t":"2023-03-01T09:43:58.9154429Z","@mt":"An error occurred during migration","@l":"Error","@x":"Npgsql.NpgsqlException (0x80004005): Failed to connect to 127.0.0.1:5432\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\r\n   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)\r\n   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|208_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)\r\n   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.UnpooledDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)\r\n   at Program.<Main>$(String[] args) in C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Messages.API\\Program.cs:line 91","SourceContext":"Program","Application":"messages-service","ExceptionDetail":{"HResult":-2147467259,"Message":"Failed to connect to 127.0.0.1:5432","Source":"Npgsql","TargetSite":"Void MoveNext()","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"IsTransient":true,"BatchCommand":null,"SqlState":null,"DbException.BatchCommand":null,"ErrorCode":-2147467259,"Type":"Npgsql.NpgsqlException"}}
{"@t":"2023-03-01T09:43:59.1732394Z","@mt":"Configured endpoint {Endpoint}, Consumer: {ConsumerType}","Endpoint":"AppUserLoggedInEvent-Messages","ConsumerType":"Messages.API.Consumers.AppUserLoggedInConsumer","SourceContext":"MassTransit","Application":"messages-service"}
{"@t":"2023-03-01T09:43:59.4337513Z","@mt":"Now listening on: {address}","address":"https://localhost:6002","EventId":{"Id":14,"Name":"ListeningOnAddress"},"SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T09:43:59.4345931Z","@mt":"Now listening on: {address}","address":"http://localhost:5002","EventId":{"Id":14,"Name":"ListeningOnAddress"},"SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T09:43:59.4353802Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T09:43:59.4359348Z","@mt":"Hosting environment: {EnvName}","EnvName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T09:43:59.4367039Z","@mt":"Content root path: {ContentRoot}","ContentRoot":"C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Messages.API","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T09:44:03.4159808Z","@mt":"Connection Failed: {InputAddress}","@l":"Warning","@x":"RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable\r\n ---> System.AggregateException: One or more errors occurred. (Connection failed)\r\n ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)\r\n--- End of stack trace from previous location ---\r\n   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)\r\n   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, ArrayPool`1 pool, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)\r\n   at MassTransit.RabbitMqTransport.ConnectionContextFactory.CreateConnection(ISupervisor supervisor) in /_/src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/ConnectionContextFactory.cs:line 86","InputAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"messages-service","ExceptionDetail":{"HResult":-2146232800,"Message":"None of the specified endpoints were reachable","Source":"RabbitMQ.Client","TargetSite":"RabbitMQ.Client.IConnection CreateConnection(RabbitMQ.Client.IEndpointResolver, System.String)","InnerException":{"Type":"System.AggregateException","HResult":-2146233088,"Message":"One or more errors occurred. (Connection failed)","Source":"RabbitMQ.Client","TargetSite":"T SelectOne[T](RabbitMQ.Client.IEndpointResolver, System.Func`2[RabbitMQ.Client.AmqpTcpEndpoint,T])","InnerException":{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"},"InnerExceptions":[{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"}]},"Type":"RabbitMQ.Client.Exceptions.BrokerUnreachableException"}}
{"@t":"2023-03-01T09:44:11.9991344Z","@mt":"Connection Failed: {InputAddress}","@l":"Warning","@x":"RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable\r\n ---> System.IO.IOException: connection.start was never received, likely due to a network timeout\r\n   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()\r\n   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)\r\n   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)\r\n   at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, ArrayPool`1 memoryPool, String clientProvidedName)\r\n   at RabbitMQ.Client.Framing.Impl.ProtocolBase.CreateConnection(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, ArrayPool`1 memoryPool, String clientProvidedName)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)\r\n   at MassTransit.RabbitMqTransport.ConnectionContextFactory.CreateConnection(ISupervisor supervisor) in /_/src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/ConnectionContextFactory.cs:line 86","InputAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"messages-service","ExceptionDetail":{"HResult":-2146232800,"Message":"None of the specified endpoints were reachable","Source":"RabbitMQ.Client","TargetSite":"RabbitMQ.Client.IConnection CreateConnection(RabbitMQ.Client.IEndpointResolver, System.String)","InnerException":{"Type":"System.IO.IOException","HResult":-2146232800,"Message":"connection.start was never received, likely due to a network timeout","Source":"RabbitMQ.Client","TargetSite":"Void StartAndTune()"},"Type":"RabbitMQ.Client.Exceptions.BrokerUnreachableException"}}
{"@t":"2023-03-01T09:44:21.1592359Z","@mt":"Bus started: {HostAddress}","HostAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"messages-service"}
{"@t":"2023-03-01T09:44:30.8134877Z","@mt":"Application is shutting down...","SourceContext":"Microsoft.Hosting.Lifetime","Application":"messages-service"}
{"@t":"2023-03-01T09:44:30.8724707Z","@mt":"Bus stopped: {HostAddress}","HostAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"messages-service"}
